name: Build React App with Provenance

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for requesting the GitHub OIDC token
      contents: read   # Required for actions/checkout
      attestations: write  # Required for writing attestations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest Witness
        run: |
          bash <(curl -s https://raw.githubusercontent.com/in-toto/witness/main/install-witness.sh)

      - name: Build React app with Witness
        run: |
          witness run --step build -o provenance.json -- npm ci && npm run build

      - name: Upload Provenance File
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: provenance.json
