name: Build React App with Witness Provenance

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Witness
        run: |
          bash <(curl -s https://raw.githubusercontent.com/in-toto/witness/main/install-witness.sh)

      - name: Generate SLSA Provenance with Witness
        run: |
          witness run --step build -o provenance.json \
            --signer-fulcio-url https://fulcio.sigstore.dev \
            --signer-fulcio-oidc-client-id sigstore \
            --signer-fulcio-oidc-issuer https://oauth2.sigstore.dev/auth \
            -- npm ci && npm run build


      - name: Upload Provenance File
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: provenance.json
